#! /bin/sh

sxhkd &
alacritty &
firefox &

bspc monitor -d 1 2 3 4 5

bspc config automatic_scheme alternate
bspc config border_width 0
bspc config window_gap   0
bspc config split_ratio  0.594

bspc rule -a Firefox -o split_dir=west
